[package]
name = "festival-gui"
version = "0.0.0"
edition = "2021"
build = "build.rs"
authors = ["hinto.janai <hinto.janai@protonmail.com>"]
description = "Festival GUI"
homepage = "https://festival.pm"
documentation = "https://github.com/hinto-janai/festival/festival-gui/README.md"
repository = "https://github.com/hinto-janai/festival"
readme = "README.md"
keywords = ["music", "player", "audio", "festival", "gui"]
license = "MIT"

[dependencies]
### Festival Internals.
shukusai = { path = "../", version = "0.0.0" }

### Personal Libraries.
benri    = { version = "0.1.5", features = ["log"] }
disk     = { version = "0.1.8", features = ["bincode2", "toml", "empty"] }
readable = { version = "0.8.1", features = ["full"] }
#readable = { path = "../../readable", features = ["full"] }
rolock   = "0.1.2"

### External patched libraries `external/`.
egui        = { version = "0.21.0", path = "../external/egui/crates/egui",        features = ["default_fonts", "serde"], default-features = false }
eframe      = { version = "0.21.0", path = "../external/egui/crates/eframe",      features = ["wgpu"],          default-features = false }
egui_extras = { version = "0.21.0", path = "../external/egui/crates/egui_extras", features = ["image"] }

### Regular libraries.
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
clap  = { version = "4.2.5", features = ["derive"] }
compact_str = "0.7.0"
crossbeam-channel = "0.5.8"
image = { version = "0.24.6", features = ["jpeg", "png"], default-features = false }
lazy_static = "1.4.0"
log   = "0.4.17"
serde = { version = "1.0.160", features = ["derive"] }
rfd = "0.11.3"
const_format = "0.2.30"
garde = "0.11.2"

# For Windows build (icon)
[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
static_vcruntime = "2.0.0"
