[package]
name = "shukusai"
version = "0.0.0"
edition = "2021"
authors = ["hinto.janai <hinto.janai@protonmail.com>"]
description = "Festival (music player) internals"
homepage = "https://festival.pm"
documentation = "https://docs.rs/shukusai"
repository = "https://github.com/hinto-janai/festival"
readme = "README.md"
keywords = ["music", "player", "audio", "festival", "shukusai"]
categories = ["multimedia"]
license = "MIT"
exclude = [
    "assets/*",
    "cmp/*",
    "external/*",
    "pgp/*",
    "utils/*",
    "CHANGELOG.md",
	".github",
	"festival-gui/*",
	"festival-web/*",
	"festivald/*",
	"festival-cli/*",
]
include = [
	"src",
	"assets/images/diagram",
    "assets/images/art/unknown.png",
	"assets/images/icon/512.png",
	"assets/images/cmp/*",
]

[workspace]
members = [
	"festival-gui",
	"festival-web",
	"festivald",
	"festival-cli",
]

# GUI
[[bin]]
name = "festival"
path = "festival-gui/src/main.rs"
doc = false

# Web
[[bin]]
name = "festival-web"
path = "festival-web/src/main.rs"
doc = false

# Daemon
[[bin]]
name = "festivald"
path = "festivald/src/main.rs"
doc = false

# CLI
[[bin]]
name = "festival-cli"
path = "festival-cli/src/main.rs"
doc = false

[profile.release]
debug = false
strip = "symbols"
codegen-units = 1
lto = true

# Run tests in `--release` mode.
#[profile.test]
#debug = false
#strip = "symbols"
#codegen-units = 1
#lto = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
### Personal libraries.
disk     = { version = "0.0.6", features = ["bincode", "toml", "empty"] }
readable = { version = "0.3.2", features = ["serde", "ignore_nan_inf"] }
rolock   = { version = "0.1.2" }

### External patched libraries `external/`.
egui        = { version = "0.21.0", path = "external/egui/crates/egui",        features = ["default_fonts"], default-features = false }
eframe      = { version = "0.21.0", path = "external/egui/crates/eframe",      features = ["wgpu"],          default-features = false }
egui_extras = { version = "0.21.0", path = "external/egui/crates/egui_extras", features = ["image"] }
lofty       = { version = "0.11.0", path = "external/lofty-rs" }

### Build dependencies.
### These aren't directly used in `shukusai`
### but for some reason, workspace builds won't
### work if not defined here, so...
clap = { version = "4", features = ["derive"] }

### Regular libraries.
anyhow = "1.0.70"
chrono = { version = "0.4.24", features = ["serde"] }
crossbeam-channel = "0.5.7"
#egui-notify = "0.5.1"
env_logger = "0.10.0"
fast_image_resize = "2.7.0"
#id3 = "1.6.0"
image = { version = "0.24.6", features = ["jpeg", "png"], default-features = false }
infer = "0.13.0"
lazy_static = "1.4.0"
log = "0.4.17"
notify = "5.1.0"
mime_guess = "2.0.4"
rand = { version = "0.8.5", features = ["small_rng"] }
#regex = "1.7.1"
#rfd = "0.11.1"
#rodio = "0.16.0"
serde_bytes = "0.11.9"
serde = { version = "1.0.158", features = ["derive"] }
#souvlaki = "0.5.3"
strsim = "0.10.0"
#symphonia = "0.5.2"
walkdir = "2.3.3"
