[package]
name = "festival"
version = "0.1.0"
edition = "2021"
authors = ["hinto.janai <hinto.janai@protonmail.com>"]
description = "Music player"
homepage = "https://festival.pm"
documentation = "https://github.com/hinto-janai/festival/src/README.md"
repository = "https://github.com/hinto-janai/festival"
readme = "README.md"
keywords = ["music", "player", "audio", "festival", "gui"]
license = "MIT"

[workspace]
members = [
	"festival-gui",
	"festival-web",
	"festivald",
	"festival-cli",
]

# Currently, only build `festival-gui`.
[[bin]]
path = "festival-gui/src/main.rs"
name = "festival"

[profile.release]
debug = false
strip = "symbols"
codegen-units = 1
lto = true

# Run tests in `--release` mode.
#[profile.test]
#debug = false
#strip = "symbols"
#codegen-units = 1
#lto = true

[dependencies]
### Personal libraries.
disk     = { version = "0.0.1", features = ["bincode", "toml", "plain"] }
readable = { version = "0.3.0", features = ["serde", "ignore_nan_inf"] }
rolock   = { version = "0.1.1" }

### External patched libraries `external/`.
egui               = { path = "external/egui/crates/egui",        features = ["default_fonts"], default-features = false }
eframe             = { path = "external/egui/crates/eframe",      features = ["wgpu"],          default-features = false }
egui_extras        = { path = "external/egui/crates/egui_extras", features = ["image"] }
#image             = { path = "external/image", features = ["png", "jpeg"] }
#fast_image_resize = { path = "external/fast_image_resize" }

### Regular libraries.
anyhow = "1.0.70"
chrono = { version = "0.4.24", features = ["serde"] }
crossbeam-channel = "0.5.7"
#egui-notify = "0.5.1"
env_logger = "0.10.0"
fast_image_resize = "2.6.0"
#id3 = "1.6.0"
image = { version = "0.24.5", features = ["jpeg", "png"], default-features = false }
infer = "0.13.0"
lazy_static = "1.4.0"
lofty = "0.11.0"
log = "0.4.17"
notify = "5.1.0"
mime_guess = "2.0.4"
#rand = "0.8.5"
#regex = "1.7.1"
#rfd = "0.11.1"
#rodio = "0.16.0"
serde_bytes = "0.11.9"
serde = { version = "1.0.158", features = ["derive"] }
#souvlaki = "0.5.3"
strsim = "0.10.0"
#symphonia = "0.5.2"
walkdir = "2.3.3"
