[default]
extend-ignore-identifiers-re = [
	"seeked",
	"Seeked",
]

[files]
extend-exclude = [
	# Doc output.
	"daemon/mdbook/docs/",
	"gui/mdbook/docs/",
	"cli/mdbook/docs/",

	"daemon/src/cert.rs",
	"external/",
]
