[book]
authors      = ["hinto-janai"]
language     =  "en"
multilingual = false
src          = "src"
title        = "festivald v0.0.0"

[build]
build-dir = "docs"

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/hinto-janai/festival"
