# Attempt downloading all files from `festival.pm`
# and verifies the SHA256SUMS & PGP signature.

name: festival.pm
on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download Windows
      run: wget --content-disposition "https://festival.pm/windows"
    - name: Download macOS
      run: wget --content-disposition "https://festival.pm/macos"
    - name: Download Linux
      run: wget --content-disposition "https://festival.pm/linux"
    - name: Download Hashes
      run: wget --content-disposition "https://festival.pm/hashes"
    - name: Download PGP key
      run: wget --content-disposition "https://festival.pm/hinto"
    - name: Verify PGP key
      run: bash -c "[[ $(sha256sum "hinto.asc" | awk '{print $1}') == 02242a2c4b4dfb2f49d30a15630a301c72910e6e5c212d432c8b7ff438696b00 ]]"
    - name: Import PGP key
      run: gpg --import hinto.asc
    - name: Verify Hashes
      run: sha256sum -c hashes.asc
    - name: Verify PGP Signature
      run: gpg --verify hashes.asc
