name: CLI Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache
      uses: actions/cache@v3.2.3
      with:
        path: |
          ~/.cargo
          target
        key: test-cli
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Test
      run: cd festival-cli && cargo test --all-features
